# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-08 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='row',
            name='content',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='submitoutput',
            name='status',
            field=models.CharField(blank=True, choices=[('Manual review', (('Reviewed', 'Reviewed'),)), ('Judge test results', [('TLE', 'Time limit exceeded'), ('OK', 'OK'), ('EXC', 'Runtime exception'), ('CERR', 'Compilation error'), ('WA', 'Wrong answer'), ('DONE', 'Done'), ('SEC', 'Security exception'), ('IGN', 'Ignored')]), ('Judge communication', [('Sent to judge', 'Sent to judge'), ('Protocol corrupted', 'Protocol corrupted'), ('Sending to judge', 'Sending to judge'), ('Judge unavailable', 'Judge unavailable')])], max_length=128),
        ),
    ]
