# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-08 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0002_auto_20180408_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='row',
            name='lang',
            field=models.IntegerField(choices=[(1, 'C++'), (2, 'Python'), (3, 'Pascal'), (4, 'Go'), (5, 'PHP'), (6, 'Rust'), (7, 'Perl'), (8, 'R')]),
        ),
        migrations.AlterField(
            model_name='sparerow',
            name='lang',
            field=models.IntegerField(choices=[(1, 'C++'), (2, 'Python'), (3, 'Pascal'), (4, 'Go'), (5, 'PHP'), (6, 'Rust'), (7, 'Perl'), (8, 'R')]),
        ),
        migrations.AlterField(
            model_name='submitoutput',
            name='status',
            field=models.CharField(blank=True, choices=[('Manual review', (('Reviewed', 'Reviewed'),)), ('Judge test results', [('SEC', 'Security exception'), ('WA', 'Wrong answer'), ('EXC', 'Runtime exception'), ('CERR', 'Compilation error'), ('DONE', 'Done'), ('TLE', 'Time limit exceeded'), ('OK', 'OK'), ('IGN', 'Ignored')]), ('Judge communication', [('Sent to judge', 'Sent to judge'), ('Protocol corrupted', 'Protocol corrupted'), ('Sending to judge', 'Sending to judge'), ('Judge unavailable', 'Judge unavailable')])], max_length=128),
        ),
    ]
