# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-09 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0003_auto_20180408_2340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='task',
            name='active',
        ),
        migrations.AlterField(
            model_name='problem',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='submitoutput',
            name='status',
            field=models.CharField(blank=True, choices=[('Manual review', (('Reviewed', 'Reviewed'),)), ('Judge test results', [('TLE', 'Time limit exceeded'), ('EXC', 'Runtime exception'), ('OK', 'OK'), ('WA', 'Wrong answer'), ('CERR', 'Compilation error'), ('SEC', 'Security exception'), ('DONE', 'Done'), ('IGN', 'Ignored')]), ('Judge communication', [('Sending to judge', 'Sending to judge'), ('Judge unavailable', 'Judge unavailable'), ('Sent to judge', 'Sent to judge'), ('Protocol corrupted', 'Protocol corrupted')])], max_length=128),
        ),
    ]
