# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-10 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0004_auto_20180409_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='variables',
            field=models.TextField(default='{}'),
        ),
    ]
