# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-16 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0006_auto_20180411_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_player',
            field=models.BooleanField(default=True),
        ),
    ]
